services:
  google-drive-mcp-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google-drive-mcp-client
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud  # For Google credentials persistence
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - GOOGLE_CREDENTIALS_PATH=/app/credentials.json
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8000:8000"  # In case the app needs to serve content
    restart: unless-stopped
    command: bash -c "python client.py gdrive_server_fixed.py"
    stdin_open: true  # Keep STDIN open for interactive queries
    tty: true  # Allocate a pseudo-TTY
